name: big-data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyspark>=3.5
  - jupyterlab
  - ipykernel
  - nbconvert
  - nbclient
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - nbformat
  - nbconvert
